import { getUserById } from "@/actions/user.action";
import { authConfig } from "@/auth.config";
import { Toaster } from "@/components/ui/sonner";
import Provider from "@/provider/Provider";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authConfig);
  let isArchived = null;

  if (session) {
    const userResponse = await getUserById(session?.user?.id!);
    isArchived = userResponse.data?.isArchived;
  }

  return (
    <html lang="en antialiased">
      <body className={inter.className}>
        <Provider>
          {isArchived ? <div>Account is disabled</div> : <>{children}</>}
        </Provider>
        <Toaster />
      </body>
    </html>
  );
}
