name: Prisma Seeding on Staging
on:
  push:
    branches:
      - staging

jobs:
  prisma-seed:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql://aaron.lim.2021:lyZErJ3jnDe2@ep-cold-silence-a1rnvgz1-pooler.ap-southeast-1.aws.neon.tech/staging?sslmode=require
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Run Prisma Generate
        run: npx prisma generate

      - name: Run Prisma DB Push
        run: npx prisma db push --force-reset --accept-data-loss    

      - name: Run Prisma Seeding
        run: npx prisma db seed

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Run Prisma Seeding"
          git push
